name: development

on:
  workflow_dispatch:
  push:
    branches:
      - 'development'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: npm test
